export const defaultTheme = {
  name: "default",
  label: "Default",
  colors: {
    background: "#f8fafc",
    foreground: "#0f172a",
    surface: "#ffffff",
    surfaceForeground: "#0f172a",
    surfaceMuted: "#f1f5f9",
    card: "#ffffff",
    cardForeground: "#0f172a",
    popover: "#ffffff",
    popoverForeground: "#0f172a",
    primary: "#2563eb",
    primaryForeground: "#ffffff",
    primaryHover: "#1d4ed8",
    secondary: "#e2e8f0",
    secondaryForeground: "#0f172a",
    secondaryHover: "#cbd5e1",
    ghost: "transparent",
    ghostForeground: "#0f172a",
    ghostHover: "#e2e8f0",
    muted: "#f1f5f9",
    mutedForeground: "#64748b",
    accent: "#14b8a6",
    accentForeground: "#0f172a",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    success: "#22c55e",
    successForeground: "#ffffff",
    warning: "#f59e0b",
    warningForeground: "#111827",
    info: "#0ea5e9",
    infoForeground: "#ffffff",
    border: "#e2e8f0",
    borderStrong: "#cbd5e1",
    input: "#cbd5e1",
    ring: "#2563eb",
    link: "#2563eb",
    linkForeground: "#1d4ed8",
    radiusLg: "1rem",
    radiusMd: "calc(1rem - 2px)",
    radiusSm: "calc(1rem - 4px)",
  },
} as const;
