export const mainTheme = {
  name: "main",
  label: "Main",
  colors: {
    background: "#f7fdf8",
    foreground: "#14281d",
    surface: "#ffffff",
    surfaceForeground: "#14281d",
    surfaceMuted: "#edf8f0",
    card: "#ffffff",
    cardForeground: "#14281d",
    popover: "#ffffff",
    popoverForeground: "#14281d",
    primary: "#16a34a",
    primaryForeground: "#ffffff",
    primaryHover: "#15803d",
    secondary: "#dcfce7",
    secondaryForeground: "#14281d",
    secondaryHover: "#bbf7d0",
    ghost: "transparent",
    ghostForeground: "#14281d",
    ghostHover: "#dcfce7",
    muted: "#edf8f0",
    mutedForeground: "#4b6b58",
    accent: "#06b6d4",
    accentForeground: "#082f49",
    destructive: "#dc2626",
    destructiveForeground: "#ffffff",
    success: "#16a34a",
    successForeground: "#ffffff",
    warning: "#d97706",
    warningForeground: "#111827",
    info: "#0284c7",
    infoForeground: "#ffffff",
    border: "#d9eadf",
    borderStrong: "#b7d4c2",
    input: "#b7d4c2",
    ring: "#16a34a",
    link: "#16a34a",
    linkForeground: "#15803d",
    radiusLg: "1rem",
    radiusMd: "calc(1rem - 2px)",
    radiusSm: "calc(1rem - 4px)",
  },
} as const;
